title: Raghav's Lab
email: your-email@example.com
description: "Logs, builds, thoughts, and systems"
baseurl: "" 
url: "https://raghav-balaji.github.io"
twitter_username: jekyllrb
github_username: raghav-balaji

theme: minima
plugins:
  - jekyll-feed
